spring.application.name=JtechApp

# --- CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# --- JWT CONFIG ---
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# --- SUPER ADMIN ---
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.nombre=${ADMIN_NOMBRE}
admin.cargo=${ADMIN_CARGO}