spring.application.name=JtechApp

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource (En memoria)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop


# jwt config

jwt.secret=!Ab@CzYAx_zXlK43uUr5*2-Zx12fFjK4
jwt.expiration=86400000

#Credenciales de superAdmin

admin.email=superadmin@jtech.com
admin.password=admin123
admin.nombre=Emmanuel
admin.cargo=Fundador