spring.application.name=JtechApp

# DataSource
spring.datasource.url=jdbc:h2:file:./JTechApp/src/main/resources/data/jtechdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true


# jwt config

jwt.secret=!Ab@CzYAx_zXlK43uUr5*2-Zx12fFjK4
jwt.expiration=86400000

#Credenciales de superAdmin

admin.email=superadmin@jtech.com
admin.password=admin123
admin.nombre=Emmanuel
admin.cargo=Fundador